### ISSUE TITLE
Tweaks to control area

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-correlation#2]
0.0.1

A great start.

Line before Panel 1: Remove dots and colon at start (I see my spec was ambiguous, sorry.) Keep the indent. Make 'r' italic

**Panel 2:** The value of r reported at right is often reported only to 1 d.p., especially when RH nudge button is used. The value shown above the handle seems correct.

Shift '_r_ of dataset' to the right, so reported value lines up under set value in white box just above. Make the reported value red, as for reported values in 'dances'

**Panel 5:** Close up a bit horizontally, including shifting the two labels a bit to the right. Make the two labels right justified. Four reported values in red.

Panel 5: X and Y italic. Reported values in red. Insert space in first two lines so the three cases of 'Slope x.x' are lined up vertically.

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.0.3

Looks great. Closing.
