### ISSUE TITLE
ESCI intro file, opened up

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-correlation#7]
I've made an 'opened up' version of ESCI intro chapters 10-16 that may be useful for seeing stuff, and checking stuff. I tried to drag and drop it below, but .xlsm files are not supported, so I'll email it.

**The 'See r' and 'Scatterplots' sheets** I have:
---removed protection, so all formulas are visible, and have displayed gridlines and headers

**For 'See r'** I have shifted some stuff, usually way off to the right, so it's visible, just below and left of the scatterplot. Mainly the pink area to do with lines, and various stuff just under that. I've also shifted the columns showing the X and Y values of the displayed points to be just to the right of the scatterplot.

Make sure radio button at red 2 is clicked on. Click button at red 4 for new data set. Watch the value of r (in green area) and the y values in column to right of scatterplot change until r is same as target. (Maybe doesn't happen when first clicked; try again.)

**For 'Scatterplots'** I have typed in the little test data set. But enter any data set in the B and C columns at left. (Use copy and 'paste special--values'.)

I have turned on the pink area to show regression info, and have shifted some stuff about the correlation line to just to the right of that pink area. This sheet does not display the regression of X on Y.

And/or send me a test data set and I'll let you know what values ESCI calculates for it.

No particular request with this issue, just hoping this file might be of some use.

**Comment by gfmoore** [comment]
Thanks.
