### ISSUE TITLE
Add test data and import data for testing

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/esci-correlation#8]
I have added a test data option. You can change the data in situ. You can also import a dataset in csv format:
'Label X', 'Label Y'
'1', '2.3'
'2.4', 3.6'
etc etc

There is a test.csv to try out in the home directory (if it will allow it.)

I haven't done any extensive testing yet as I'm watching the most boring Tour de France ever. They are having a holiday.

**Comment by gdcumming** [comment]
0.0.9

Thanks. I haven't tried csv files but have tried a fair number of typed in variations against ESCI. Within the 2 dp limits, everything looks accurate: M, SD, r, slopes.
