### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-correlation#9]
0.0.9

TIps (and a couple of small tweaks) please.

**Lines 2 and 3** 
'correlation':  The appearance of data sets can vary widely, despite all having the same _r_
'See data sets all with the same _r_': same as above

**Panel 1**
'1 _N_': Size of data set
'slider [...]': Select _N_, within 4 to 300

**Panel 2**
'2 Data set correlation _r_': The correlation, _r_, of _X_ and _Y_ in the data set
'slider [...]': Select _r_
Tweak please: '_r_ of data set' not '_r_ of dataset'
'_r_ of data set [...]': _r_ for the displayed data set

**Panel 3**
'3': Click for a new data set with the same _r_. Red points signal points beyond the display area
button: same as above
'...with correlation _r_': same as above

**Panel 4**
Tweak please: 'Display' not 'Click to display'
'Display': Choose what is displayed in the figure
'[ ] Value of _r_ in the figure': _r_ for this data set
'[ ] Cross through means': Cross through mean of _X_, mean of _Y_
'[ ] Marginal distributions': Marginal distributions of _X_ and _Y_ displayed next to axes. Solid black dots at either end signal points beyond the display area.

**Panel 5**
'5 Descriptive statistics [ ]': Display mean and SD of _X_ and _Y_

**Panel 6**
'6 Display lines [ ]': Choose lines to display

'Y against X': Linear regression of _Y_ against _X_
'Slope [ ...]': Gradient of this regression line

'X against Y': Linear regression of _X_ against _Y_
'Slope [ ...]': Gradient of this regression line

'Correlation line': Line for _r_ = 1.0, or -1.0
'Slope [ ...]': Gradient of this line is the geometric mean of the above two gradients, with appropriate sign

**Comment by gfmoore** [comment]
Done.

**Comment by gdcumming** [comment]
0.0.10

Perfect. Thanks.

Just one thing--the values for slopes have become blue. Can we have them red again, our standard for reported values?

**Comment by gfmoore** [comment]
oops, reinstated. Because I had two class statements, one for tips and one for red, can only have one class= statement.

**Comment by gdcumming** [comment]
0.0.11

Looks good. Closing
